export const storageKeys = {
  accessToken: "smartconsig:access_token",
  customerName: "smartconsig:cliente_nome",
  customerDocument: "smartconsig:cliente_cpf",
  customerContact: "smartconsig:cliente_contato",
  operatorId: "smartconsig:id_operador",
  operatorName: "smartconsig:nome_operador",
  operatorUsername: "smartconsig:email_operador",
  operatorContact: "smartconsig:contato_operador",
  operatorTeamId: "smartconsig:id_time_operador",
  operatorTeamName: "smartconsig:nome_time_operador",
  utmSource: "smartconsig:utm_source",
  utmCampaign: "smartconsig:utm_campaign",
  utmId: "smartconsig:utm_id",
  utmContent: "smartconsig:utm_content",
  utmMedium: "smartconsig:utm_medium",
  publicServerCustomerName: "smartconsig:servidor_nome",
  publicServerCustomerContact: "smartconsig:servidor_contato",
  publicServerCustomerDocument: "smartconsig:servidor_cpf",
}